### ISSUE TITLE
音频格式不支持

### ISSUE THREAD

**Issue by nature1317** [Jackiexiao/MTTS#10]
INFO    : Start montreal forced align
Setting up corpus information...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 146, in validate_args
  File "aligner/command_line/align.py", line 84, in align_corpus
  File "aligner/corpus.py", line 309, in __init__
  File "aligner/corpus.py", line 151, in get_sample_rate
  File "wave.py", line 499, in open
  File "wave.py", line 163, in __init__
  File "wave.py", line 143, in initfp
  File "wave.py", line 260, in _read_fmt_chunk
wave.Error: unknown format: 3
Failed to execute script align
WARNING : --Miss: ./tang/output/textgrid/mandarin_voice/1.TextGrid
INFO    : the label files are in ./tang/output/labels
INFO    : the error log is in ./tang/output/mtts.log

**Comment by Jackiexiao** [comment]
see this [issue](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner/issues/57) on Montreal-forced-aligner
