### ISSUE TITLE
No such file or directory: '/home/top/Documents/MFA/wav/corpus_data/split1/feats.0.scp'

### ISSUE THREAD

**Issue by shartoo** [Jackiexiao/MTTS#19]
umber of speakers in corpus: 1, average number of utterances per speaker: 1340.0
Creating dictionary information...
Setting up corpus_data directory...
Generating base features (mfcc)...
[3581] Failed to execute script align
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 224, in <module>
  File "aligner/command_line/align.py", line 181, in validate_args
  File "aligner/command_line/align.py", line 129, in align_corpus
  File "aligner/aligner/pretrained.py", line 61, in __init__
  File "aligner/aligner/base.py", line 50, in __init__
  File "aligner/aligner/pretrained.py", line 79, in setup
  File "aligner/aligner/base.py", line 55, in setup
  File "aligner/features/config.py", line 153, in generate_features
  File "aligner/features/config.py", line 141, in generate_base_features
  File "aligner/corpus.py", line 813, in combine_feats
FileNotFoundError: [Errno 2] No such file or directory: '/home/top/Documents/MFA/wav/corpus_data/split1/feats.0.scp'

**Comment by Jackiexiao** [comment]
Can you give more information? for example,  a wav file and text?

**Comment by shartoo** [comment]
```
cd montreal-forced-aligner/lib/thirdparty/bin 
rm -rf libopenblas.so.0
 ln -s ../../libopenblasp-r0-8dca6697.3.0.dev.so libopenblas.so.0
```
This can fix the problem
