### ISSUE TITLE
duplicated file names?

### ISSUE THREAD

**Issue by homink** [Jackiexiao/MTTS#2]
Hi,

I am looking into merlin for Korean extension and found your work. It is AMAZING. I tried your script and found the following error. Could you have a look if I am misleading?

Best,
Homin

```
$ ./run_demo.sh 
Setting up corpus information...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
  File "aligner/command_line/align.py", line 146, in validate_args
  File "aligner/command_line/align.py", line 84, in align_corpus
  File "aligner/corpus.py", line 320, in __init__
aligner.exceptions.CorpusError: Files with the same file name are not permitted. Files with the same name are: data/thchs30_250_demo/output/wav/mandarin_voice/A11_0.wav, data/thchs30_250_demo/output/wav/mandarin_voice/wav/A11_0.wav.
Failed to execute script align
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_0.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_1.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_2.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_3.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_4.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_5.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_6.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_7.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_8.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_9.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_10.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_11.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_12.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_13.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_14.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_15.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_16.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_17.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_18.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_19.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_20.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_21.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_22.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_23.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_24.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_25.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_26.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_27.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_28.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_29.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_30.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_31.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_32.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_33.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_34.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_35.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_36.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_37.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_38.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_39.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_40.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_41.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_42.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_43.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_44.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_45.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_46.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_47.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_48.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_49.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_50.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_51.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_52.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_53.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_54.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_55.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_56.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_57.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_58.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_59.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_60.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_61.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_62.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_63.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_64.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_65.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_66.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_67.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_68.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_69.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_70.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_71.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_72.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_73.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_74.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_75.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_76.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_77.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_78.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_79.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_80.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_81.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_82.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_83.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_84.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_85.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_86.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_87.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_88.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_89.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_90.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_91.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_92.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_93.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_94.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_95.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_96.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_97.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_98.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_99.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_100.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_101.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_102.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_103.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_104.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_105.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_106.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_107.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_108.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_109.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_110.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_111.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_112.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_113.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_114.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_115.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_116.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_117.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_118.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_119.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_120.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_121.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_122.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_123.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_124.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_125.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_126.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_127.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_128.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_129.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_130.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_131.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_132.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_133.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_134.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_135.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_136.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_137.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_138.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_139.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_140.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_141.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_142.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_143.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_144.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_145.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_146.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_147.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_148.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_149.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_150.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_151.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_152.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_153.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_154.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_155.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_156.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_157.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_158.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_159.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_160.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_161.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_162.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_163.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_164.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_165.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_166.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_167.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_168.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_169.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_170.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_171.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_172.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_173.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_174.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_175.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_176.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_177.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_178.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_179.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_180.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_181.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_182.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_183.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_184.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_185.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_186.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_187.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_188.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_189.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_190.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_191.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_192.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_193.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_194.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_195.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_196.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_197.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_198.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_199.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_200.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_201.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_202.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_203.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_204.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_205.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_206.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_207.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_208.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_209.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_210.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_211.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_212.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_213.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_214.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_215.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_216.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_217.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_218.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_219.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_220.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_221.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_222.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_223.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_224.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_225.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_226.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_227.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_228.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_229.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_230.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_231.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_232.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_233.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_234.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_235.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_236.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_237.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_238.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_239.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_240.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_241.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_242.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_243.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_244.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_245.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_246.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_247.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_248.TextGrid
--Miss: data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_249.TextGrid
```

**Comment by yanyanxixi** [comment]
aligner.exceptions.CorpusError: Files with the same file name are not permitted. Files with the same name are: data/thchs30_250_demo/output/wav/mandarin_voice/A11_0.wav, data/thchs30_250_demo/output/wav/mandarin_voice/wav/A11_0.wav.
Failed to execute script align

becase：this line in mtts.py
os.system('ln -s %s %s/wav/mandarin_voice' % (wav_dir_real_path, output_path))
will link a  "mandarin_voice/wav" if mandrain_voice is existed

**Comment by Jackiexiao** [comment]
@yanyanxixi Thx, I have fixed this symbolic bug, @homink This project only work for mandarin, it doesn't support Korean but I think you can write your own Korean frontend, it isn't difficult

**Comment by homink** [comment]
@Jackiexiao Thanks!

If you don't mind, could you describe more details of how to calculate and measure 'a','b','d','s'? I found a brief info from src/mandarin_frontend.py. 

        sfsfile: absolute path of sfs file (alignment file). A sfs file
            example(measure time by 10e-7 second, 12345678 means 1.2345678
            second)
            --------
            239100 s 
            313000 a 
            323000 d
            400000 b 
            480000 s 
            ---------
            a stands for consonant
            b stands for vowel
            d stands for silence that is shorter than 100ms
            s stands for silence that is longer than 100ms


But, A11_0.TextGrid and A11_0.sfs look not synchronized in terms of timestamp. For example, such 14300000 (1.430) is not found in A11_0.TextGrid. Could you help me what I am misleading here?

```
head -30 ./data/thchs30_250_demo/output/textgrid/mandarin_voice/A11_0.TextGrid
File type = "ooTextFile"
Object class = "TextGrid"

xmin = 0.0
xmax = 7.8
tiers? <exists>
size = 2
item []:
        item [1]:
                class = "IntervalTier"
                name = "words"
                xmin = 0.0
                xmax = 7.8
                intervals: size = 33
                        intervals [1]:
                                xmin = 0.0
                                xmax = 1.100
                                text = ""
                        intervals [2]:
                                xmin = 1.100
                                xmax = 1.350
                                text = "lv4"
                        intervals [3]:
                                xmin = 1.350
                                xmax = 1.460
                                text = "shi4"
                        intervals [4]:
                                xmin = 1.460
                                xmax = 1.650
                                text = "yang2"

$ head ./data/thchs30_250_demo/output/sfs/A11_0.sfs
11000000 s
12400000 a
13500000 b
14300000 a
14600000 b
15100000 a
16500000 b
17600000 a
18300000 b
19000000 a
```

**Comment by Jackiexiao** [comment]
@homink The TextGrid file generate two different level of alignment, one is `words`, another one is `phones`, mandarin words like `lv4` can separate into phones like `l` and `v4`, `l` is consonant and `v4` is vowel.

You can find the phones alignment in the TextGrid file start with 
```
        item [2]:
                class = "IntervalTier"
                name = "phones"
```

**Comment by homink** [comment]
Great reply! Thank you!!
