### ISSUE TITLE
Failed to execute script align

### ISSUE THREAD

**Issue by chwbin** [Jackiexiao/MTTS#21]
按照你的流程步骤（数据和程序都下载下来了），执行：run_demo.sh报错：
INFO    : Start montreal forced align
/home/chwbin/workplace/MTTS-master/tools/montreal-forced-aligner/bin/mfa_align data/thchs30_250_demo/output/wav /home/chwbin/workplace/MTTS-master/misc/mandarin_mtts.lexicon /home/chwbin/workplace/MTTS-master/misc/thchs30.zip data/thchs30_250_demo/output/textgrid
Setting up corpus information...
Number of speakers in corpus: 1, average number of utterances per speaker: 250.0
Creating dictionary information...
Setting up training data...
Calculating MFCCs...
Traceback (most recent call last):
  File "aligner/command_line/align.py", line 186, in <module>
    args.acoustic_model_path.lower(), ', '.join(PRETRAINED_LANGUAGES))))
  File "aligner/command_line/align.py", line 146, in validate_args
    a.export_textgrids()
  File "aligner/command_line/align.py", line 93, in align_corpus
    else:
  File "aligner/aligner/pretrained.py", line 71, in __init__
    return os.path.join(self.temp_directory, 'model')
  File "aligner/aligner/pretrained.py", line 117, in setup
  File "aligner/aligner/base.py", line 80, in setup
    '''
  File "aligner/corpus.py", line 970, in initialize_corpus
  File "aligner/corpus.py", line 848, in create_mfccs
    self.write()
  File "aligner/corpus.py", line 859, in _combine_feats
    self.figure_utterance_lengths()
FileNotFoundError: [Errno 2] No such file or directory: '/home/chwbin/Documents/MFA/wav/train/mfcc/raw_mfcc.0.scp'
Failed to execute script align

**Comment by Jackiexiao** [comment]
`sudo apt-get install libatlas3-base`

**Comment by marsoyang1** [comment]
centos have not this package，how to deal this？

**Comment by Jackiexiao** [comment]
I am not sure if this helps. --> https://mageia.pkgs.org/6/mageia-core-release-i586/libatlas3-base-3.10.2-9.mga6.i586.rpm.html

**Comment by shanmukhanand** [comment]
i am facing the same issue...is libatlas3-base installation works?
