### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by jasonfengzf** [Jackiexiao/MTTS#31]
Hi，i got this issue when i inputted the code : bash run_demo.sh .How can i do?Thanks！

Traceback (most recent call last):
  File "aligner/command_line/align.py", line 224, in <module>
  File "aligner/command_line/align.py", line 181, in validate_args
  File "aligner/command_line/align.py", line 117, in align_corpus
  File "aligner/corpus.py", line 496, in speaker_utterance_info
ZeroDivisionError: division by zero
[14920] Failed to execute script align
Traceback (most recent call last):
  File "src/mtts.py", line 276, in <module>
    args.acoustic_model_path)
  File "src/mtts.py", line 236, in generate_label
    _mfa_align(txtlines, wav_dir_path, output_path, acoustic_model_path)
  File "src/mtts.py", line 140, in _mfa_align
    raise OSError('Failed to run forced align tools, check if you install'
OSError: Failed to run forced align tools, check if you installmontreal-forced-aligner correctly

**Comment by YihuaLiang95** [comment]
Did you solve this problem? I also got this problem

**Comment by YihuaLiang95** [comment]
If your run this code on Windows, it could be fixed by replace the 2nd parameters when execute montreal forced aligner.  All commands related to system operation i.e. `mkdir` should be converted into windows format

**Comment by e0397123** [comment]
> If your run this code on Windows, it could be fixed by replace the 2nd parameters when execute montreal forced aligner. All commands related to system operation i.e. `mkdir` should be converted into windows format

Hi, I have also encountered this problem on ubuntu. May I know exactly you solve it? Thanks in advance.
